# Set the terminal inside tmux to use 256 colours
set -g default-terminal "tmux-256color"

# Activate true color support
set-option -sa terminal-overrides ",xterm*:Tc"

# Lower latency when pressing the <Escape> button
set -s escape-time 0

# Set mouse support
set -g mouse on
