[project]
name = "devcontainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andon Andonov", email = "87700128+doks5@users.noreply.github.com" },
]
requires-python = ">=3.13"
dependencies = ["textual>=8.2.8"]

[project.scripts]
devcontainer = "app:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."
module-name = "app"
