[project]
name = "devcontainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andon Andonov", email = "andon_b_andonov@proton.me" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
devcontainer = "devcontainer:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
